### Recuperar info del pokemon ditto
GET http://localhost:4000/pokemon/ditto


### Para crear un Pokemon
POST http://localhost:4000/pokemon
Content-Type: application/json

{
	"name":"ditto",
	"type":"normal",
	"moves": [
		"trasnform"
	]
}